version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Helsinki"
      
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "typescript"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Helsinki"
