name: Deploy to Heroku

on:
  push:
    branches:
      - main
    # paths:
    #   - server/**

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - name: Login to Heroku
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Build and push
        run: heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Release
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
